### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by B0073D** [Vitzual/Vectorio#90]
There is no license visible, I am not sure what your intent is here but if this is supposed to be an open source game it would be best to pick an appropriate license that suits your needs.

**Comment by Vitzual** [comment]
Originally the repository had a GPL3 license, but I had to remove it since the license was void due to their being external dependencies I wasn't able to include in the source code. (brought to my attention in issue #75) A more fitting license for the repository would be an MIT license, but I would like to finish the Early Access version first before adding it. 

In the meantime, the repository is a great way for the community to follow progress and see what's being worked on.
